# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21d6d1b82aab818ba74b412988cfe607357ce27d122c62eecd251c1ae79ca097d8a65c1e8e849a6feaf48abe0413639cda5ec780d0ae44b600a9b586b0605b1

test:
  secret_key_base: 361f83ae3831d183cee2376d45cc0fe9baefcfd7f2eb2a8847cf4642800ba727e676fd1c6a927922a3784242fce4caf6d133cf07970459427ebc7c70e5905340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
